# simple configuration for dependabot to analyze the packages updates
version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 5
